### ISSUE TITLE
How to Sort article list by date

### ISSUE THREAD

**Issue by cricrazy** [mrgodhani/raven-reader#304]
**Is your feature request related to a problem? Please describe.**
Currently, I cannot sort the articles list by date.

**Describe the solution you'd like**
Allow option to sort it based on date.

**Comment by juri-sinitson** [comment]
The default sorting is wrong since the version 0.4.1. previous version(s) the default sorting of articles was descending by date and it was fine. The newest articles were always above.

Now the sorting is buggy. Since the version 0.4.1 the articles are sorted by the string representation of the date. Example: an hour ago, a month ago, ..., a month ago, a day ago, 8 day ago. This sorting does not make any sense and you have to scroll unnecessary lot.

**Comment by cricrazy** [comment]
@juri-sinitson I agree. It seems very random. Hopefully, there will be a fix for it.

**Comment by mrgodhani** [comment]
https://github.com/mrgodhani/raven-reader/releases/tag/v0.4.5 solved

**Comment by jcalfee** [comment]
v0.5.1 appears to have this bug again..

**Comment by sugguy** [comment]
Still an issue
